# Generated by Django 5.0.4 on 2024-04-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer_text',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_option',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='option_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option_4',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(blank=True),
        ),
    ]
