# Generated by Django 5.0.4 on 2024-04-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0002_remove_question_answer_text_question_correct_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.TextField(default=0),
        ),
    ]
