# Generated by Django 5.0.4 on 2024-04-10 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Players', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Player_Groups',
            new_name='Player_Group',
        ),
    ]
