# Generated by Django 5.0.4 on 2024-04-10 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Players', '0003_player_individual_group_player_individual_player_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_individual',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='Players.player_group'),
        ),
    ]
