# Generated by Django 5.0.4 on 2024-04-10 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Players', '0005_alter_player_individual_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Player_Group',
            new_name='Group',
        ),
        migrations.RenameModel(
            old_name='Player_Individual',
            new_name='Individual',
        ),
        migrations.RenameModel(
            old_name='Player_Stat',
            new_name='Stat',
        ),
    ]
