# Generated by Django 5.0.4 on 2024-04-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Players', '0007_remove_individual_player_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='alloted_team_group',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='stat',
            name='wicketkeeper',
            field=models.BooleanField(default=False),
        ),
    ]
