# Generated by Django 5.0.4 on 2024-04-17 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Players', '0016_alter_group_alloted_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='alloted_team_group',
            field=models.IntegerField(default=-1),
        ),
    ]
