# Generated by Django 5.0.4 on 2024-04-17 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Players', '0017_group_alloted_team_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='alloted_team_group',
        ),
    ]
