# Generated by Django 5.0.4 on 2024-04-17 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Players', '0019_alter_group_alloted_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='group_stat',
            new_name='group_points',
        ),
    ]
