# Generated by Django 5.0.4 on 2024-04-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.IntegerField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=40)),
                ('purse_value', models.FloatField(default=0.0)),
            ],
        ),
    ]
