# Generated by Django 5.0.4 on 2024-04-23 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0002_remove_student_student_name_and_more'),
    ]

    operations = [
    ]
