# Generated by Django 5.0.4 on 2024-04-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='time_taken',
            field=models.IntegerField(default=900),
        ),
    ]
