# Generated by Django 5.0.4 on 2024-04-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0003_team_correct_answers_team_time_taken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='time_taken',
        ),
        migrations.AddField(
            model_name='team',
            name='points_scored',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='purse_value',
            field=models.FloatField(default=40),
        ),
    ]
