# Generated by Django 5.0.4 on 2024-04-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0003_auto_20240423_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
        migrations.AddField(
            model_name='student',
            name='student_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_rollno',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='StudentData',
        ),
    ]
